---
title: "Stocks Market"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stocks Predict - classification in R 
#### Eyal Gat, Mor Anavi & Ori Dahari
```{r, include=FALSE}
library(binhf)
library(quantmod)
library(xts)
library("randomForest")
library("gbm")

```


#
##Function that compute variables to stock
```{r}
add.data.frame <- function(Split.df){

 
 #Change between yesterday close-today close
yesterday_closePrice= shift(v=as.numeric(Split.df$Close), places=1, dir="right")
Change= (Split.df$Close-yesterday_closePrice)/yesterday_closePrice*100
Change[1]=0

  #Change between yesterday close-today open price
Open_Change= (Split.df$Open-yesterday_closePrice)/yesterday_closePrice*100
Open_Change[1]=0

#Change between yesterday todey open-today close price
Change_Within= Change-Open_Change

#Ratio between high,low,open,close
High_Close= Split.df$High/Split.df$Close

Low_Close=  Split.df$Low/ Split.df$Close

High_Low=  Split.df$High/ Split.df$Low

High_Open=  Split.df$High/ Split.df$Open

Low_Open=  Split.df$Low/ Split.df$Open

EMA.Fast <- EMA(Split.df$Close, n=20)
EMA.Medium <- EMA(Split.df$Close, n=120) 
EMA.Slow <- EMA(Split.df$Close, n=200) 
EMA.10=  EMA(Split.df$Close, n=10)
EMA.50= EMA(Split.df$Close, n=50)
EMA.80= EMA(Split.df$Close, n=80)
EMA.100= EMA(Split.df$Close, n=100)
EMA.150= EMA(Split.df$Close, n=150)
fast_detrend_ma <- EMA.Fast - EMA.Medium
slow_detrend_ma <- EMA.Medium - EMA.Slow
CCI.IND <- CCI(HLC=Split.df[,c("High","Low","Close")],n=100)
RSI.Fast <- RSI(price=Split.df$Close,n=10)
RSI.Slow <- RSI(price=Split.df$Close,n=100)
RSI.Medium= RSI(price=Split.df$Close,n=30)
RSI.20= RSI(price=Split.df$Close,n=20)
RSI.50= RSI(price=Split.df$Close,n=50)
RSI.80= RSI(price=Split.df$Close,n=80)
RSI.Diff.Med <- RSI.Medium-RSI.Slow
RSI.Diff.Fast <- RSI.Fast-RSI.Medium
ROC.Fast <- ROC(Split.df$Close,n=10)
ROC.Medium <- ROC(Split.df$Close,n=100)
ROC.Slow <- ROC(Split.df$Close,n=200)
ROC.Diff <- ROC.Fast-ROC.Medium
ROC.Diff.Medium <- ROC.Medium-ROC.Slow
CV.IND=chaikinVolatility(HL=Split.df[,c("High","Low")],n=100)

Split.df <- data.frame(Split.df[],Change,Open_Change,Change_Within,High_Close,Low_Close,High_Low,High_Open,Low_Open,EMA.Fast,EMA.Medium,EMA.Slow, fast_detrend_ma,slow_detrend_ma,CCI.IND,RSI.Fast,RSI.Slow,RSI.Diff.Med,RSI.Diff.Fast,ROC.Fast,ROC.Slow,ROC.Diff,EMA.10,EMA.50,EMA.80,EMA.100,EMA.150,CV.IND,RSI.20,RSI.50,RSI.80,RSI.Medium,ROC.Medium,ROC.Diff.Medium)


return(Split.df)
  
}



```

#Adding technical indicators to stock 
```{r}
addInd<- function(data2){
  
    data2$LogClose <- log(data2$Close)  
  data2$MACD <- MACD(data2$Close)
 data2$will <- williamsAD(data2[,c("High","Low","Close")])
 data2$cci <-  CCI(data2[,c("High","Low","Close")])
 data2$STOCH <- stoch(data2[,c("High","Low","Close")])
 data2$Aroon <- aroon(data2[, c("High","Low")])
 data2$ATR <- ATR(data2[,c("High","Low","Close")]) 

 data2$SMI <- SMI(data2[, c("High","Low","Close")])
 data2$BB <- BBands(data2[, c("High","Low","Close")])
 data2$ChaikinVol <-Delt(chaikinVolatility(data2[, c("High","Low")]))
 data2$CLV <- EMA(CLV(data2[, c("High","Low","Close")]))
 data2$Volatility <- volatility(data2[, c("Open","High","Low","Close")], calc="garman")
  
 return(data2)
  
}
```


# Function that compute the Y predict to stock:
```{r}
computeY <- function(df){
 boolean=FALSE
  for(i in 1:1){
     closePriceXdays=shift(v=as.numeric(df$Close ), places=1, dir="left")
       boolean = boolean | (closePriceXdays-df$Close)/df$Close*100>0
    }
  vectorY=ifelse(boolean ,1,0)
  
 return( vectorY )
  
  
}

```


# Calculate the Profit and Loss using the RF predict model:
```{r}
ProfitLoss_Calculator <- function(objDF) {
        # make column names generic so they can handle any symbol
        
        
        current_long <- 0
        current_short <- 0
        
        for (ind in seq(1,nrow(objDF))) {
                if (!is.na( objDF$Long_Trades[ind])) {
                        # first trade should be an entry, last trade an exit
                        if ((current_long==0 & objDF$Long_Trades[ind] > 0) | (current_long !=0)) {
                                # next trade should be opposite sign of previous trade (entry -> exit)
                                if (sign(objDF$Long_Trades[ind]) != sign(current_long)) {
                                        current_long <- as.numeric(objDF$Long_Trades[ind])
                                        print(paste('Long', current_long))
                                }
                        }
                
                        if (current_long != as.numeric(objDF$Long_Trades[ind]))
                                objDF$Long_Trades[ind] <- 0
                }
       
          
              #  if (objDF$Short_Trades[ind] !=0) {
                        # first trade should be an entry
               #         if ((current_short==0 & objDF$Short_Trades[ind] > 0) | (current_short !=0)) {
                                # next trade should be opposite sign of previous trade (entry -> exit)
                #                if (sign(objDF$Short_Trades[ind]) != sign(current_short)) {
                 #                       current_short <- as.numeric(objDF$Short_Trades[ind])
                  #                      print(paste('Short', current_short))
                   #             }
                    #    }
                     #   if (current_short != as.numeric(objDF$Short_Trades[ind]))
                      #          objDF$Short_Trades[ind] <- 0
                }
 
        
        # trim to be even, if not add last close held in chart
        if ((!length(objDF$Long_Trades[objDF$Long_Trades != 0])%% 2) == 0)
               objDF$Long_Trades[length(objDF$Close)] <- -1 * objDF$Close[length(objDF$Close)]
      #  if ((!length(objDF$Short_Trades[objDF$Short_Trades != 0])%% 2) == 0)
      #         objDF$Short_Trades[length(objDF$Close)] <- -1 * objDF$Close[length(objDF$Close)]
      #  View(objDF$Long_Trades)
        print(paste('Final Longs:',round(sum(objDF$Long_Trades * -1 , na.rm = TRUE),2)))
     #   print(paste('Final Shorts:',round(sum(objDF$Short_Trades),2)))
        
   
        # plot trade entries and exits
      #  par(mfrow=c(2,1))
        
        plot(objDF$Close ,main='Long Trades', subset="")
        events <- xts("80/20", 
              (c(index(MainStock[bound,]))))
        addEventLines(events, srt=90, pos=2,lty = 1, lwd = 1, col = 1)
        
        points(ifelse(objDF$Long_Trades > 0, objDF$Long_Trades, NA), col='green', cex=1.5, pch=16)
        points(ifelse(objDF$Long_Trades < 0, objDF$Long_Trades * -1, NA), col='red', cex=1.5, pch=15)
        
      #  plot(objDF, main='Short Trades')
       # points(ifelse(objDF$Short_Trades > 0, objDF$Short_Trades, NA), col='green', cex=1.5, pch=16)
        #points(ifelse(objDF$Short_Trades < 0, objDF$Short_Trades * -1, NA), col='red', cex=1.5, pch=15)
}

```



# Choose stocks and build RF and GBM predict models:
```{r}
#install.packages('quantmod')
#install.packages('binhf')
#library(binhf)
#library(quantmod)
#library(xts)
getSymbols('GOOGL', src='yahoo')

MainStock=GOOGL
colnames(MainStock) <- c("Open", "High", "Low", "Close", "Volume", "Adj")
Stock=MainStock

## preper the data:
Stock=addInd(Stock)
Stock=add.data.frame(Stock)

##Choose what to predict (build Y)
Stock$Up_Down=computeY(Stock)


   # Split to train 80% and test 20%
  bound <- floor((nrow(Stock)/5)*4)
  df.train <- Stock[1:bound, ]
    df.test <- Stock[(bound+1):nrow(Stock), ]
    
    
    ### Random Forest (RF)
    #### Model learning on Train data
    #### Run the tree model for all predictors, and then view the model summary and plot:
    
    #install.packages("randomForest")
    #library(randomForest)
    
    set.seed(9) #RF includes random selection. Repeat same seed to repeat the RF
    Stock.RF <- randomForest(Up_Down ~. , data = df.train ,na.action=na.exclude) #Train with all predictors
    fitted.results.RF=predict(Stock.RF,df.test)
  
   # plot(Stock.RF)
    #importance(Stock.RF)
    varImpPlot(Stock.RF)
    
    threshold <- 0.6
    prediction <- ifelse(fitted.results.RF > threshold,1,0)
  
    
    cross.table <- table(prediction, df.test$Up_Down )
    cross.table
    
    ###From the table you can calculate manualy all KPIs:
    
    acc=(cross.table[1,1]+cross.table[2,2])/ (cross.table[1,1]+cross.table[2,2]+cross.table[1,2]+cross.table[2,1]) #accuracy 
    prec=cross.table[2,2]/(cross.table[2,2]+cross.table[2,1]) #precision
    rec=cross.table[2,2]/(cross.table[2,2]+cross.table[1,2]) #Recall
    
    summary_data=data.frame(Accuracy=acc ,Precision=prec , Recall=rec)
    summary_data

   # priceTrainVectorLong=df.train$Up_Down*df.train$Close
    Point= append(df.train$Up_Down,prediction)
    
     
     #library("gbm")

    ###GBM:
    
    set.seed(7) #GBM includes random selection. Repeat same seed to repeat the RF
    Stock.GBM <- gbm (Up_Down ~ . , data = df.train, n.trees = 1000, interaction.depth = 4, shrinkage = 0.2, verbose = F) #gbm 
    fitted.results.GBM <- predict(Stock.GBM,df.test, n.trees = 1000)
      prediction.GBM <- ifelse(fitted.results.GBM > threshold,1,0)
 
    cross.table.GBM <- table(prediction.GBM, df.test$Up_Down )
    cross.table.GBM
    
    ###From the table you can calculate manualy all KPIs:
    
    acc.GBM=(cross.table.GBM[1,1]+cross.table.GBM[2,2])/ (cross.table.GBM[1,1]+cross.table.GBM[2,2]+cross.table.GBM[1,2]+cross.table.GBM[2,1]) #accuracy 
    prec.GBM=cross.table.GBM[2,2]/(cross.table.GBM[2,2]+cross.table.GBM[2,1]) #precision
    rec.GBM=cross.table.GBM[2,2]/(cross.table.GBM[2,2]+cross.table.GBM[1,2]) #Recall
    
    summary_data.GBM=data.frame(Accuracy=acc.GBM ,Precision=prec.GBM , Recall=rec.GBM)
    summary_data.GBM  
      
    
    
    
# look for long entries
Long_Trades <- ifelse(
  Point  == 0, NA,  MainStock$Close)

Long_Trades <- ifelse(shift(v=as.numeric(Point), places=2, dir="right")==1& shift(v=as.numeric(Point), places=1, dir="right")==0 & Point==0  , -1 * MainStock$Close, Long_Trades)

#exit_Long_Trades <- ifelse(shift(v=as.numeric(Point), places=2, dir="right")==1& shift(v=as.numeric(Point), places=1, dir="right")==0 & Point==0  , MainStock$Close,NA)

# look for short entries
#Short_Trades <- ifelse(     Point==0, MainStock$Close, NA) 

MainStock$Long_Trades=Long_Trades
#MainStock$exitLong=exit_Long_Trades
ProfitLoss_Calculator(MainStock[index(MainStock)>=(index(MainStock[bound,])),])

plot(MainStock$Close ,subset="")
events <- xts("80/20", 
              (c(index(MainStock[bound,]))))
addEventLines(events, srt=90, pos=2,lty = 1, lwd = 1, col = 1)
points(MainStock$Long_Trades, col='green', cex=2, pch=18 )
points(MainStock$exitLong, col='red', cex=2.5, pch=18)

```

